""""" ALL PLUGINS """""
if has('nvim')
call plug#begin('~/.config/nvim/plugged')
else
call plug#begin('~/.vim/plugged')
endif
    " Make things pretty
    Plug 'itchyny/lightline.vim'
    Plug 'mengelbrecht/lightline-bufferline'
    if has('nvim')
        Plug 'shaunsingh/nord.nvim'
    else
        Plug 'arcticicestudio/nord-vim'
    endif
    Plug 'ryanoasis/vim-devicons'
    
    " fuzzy search
    Plug 'junegunn/fzf.vim'
    Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }

    " git stuff
    if has('nvim') || has('patch-8.0.902')
      Plug 'mhinz/vim-signify'
    else
      Plug 'mhinz/vim-signify', { 'branch': 'legacy' }
    endif
    Plug 'tpope/vim-fugitive'

    " Misc things to make line easier
    Plug 'Yggdroot/indentLine'
    Plug 'tpope/vim-commentary'
    Plug 'preservim/nerdtree'
    Plug 'NoahTheDuke/vim-just'
    Plug 'christoomey/vim-tmux-navigator'
    Plug 'junegunn/vim-peekaboo'
    Plug 'unblevable/quick-scope'
call plug#end()


""""" BASIC SETUP """""
set clipboard=unnamed
set relativenumber
set ruler
set showcmd
set cursorline
filetype plugin indent on
set wildmenu
set showmatch
set hidden
set autoindent
set backspace=indent,eol,start
set hlsearch
set incsearch
set autoread
set nowrap
" Control Tabs
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set shiftround
" Colors
syntax enable
colorscheme nord
" No backup files to clean up
set noswapfile
set nobackup
set wb
" Persistent Undo
set undodir=~/.vim/undo_dir
set undofile
" reduce time waiting for timeout to end
set timeoutlen=1000
set ttimeoutlen=50
 " set number of screen lines to keep above/below the cursor
set scrolloff=8 
 
" Easy buffer switching
if !has('nvim')
    execute "set <A-h>=\eh"
    execute "set <A-l>=\el"
endif
nnoremap <A-l> :bn<CR>
nnoremap <A-h> :bp<CR>
nnoremap <Leader>d :bp \| bd #<CR>


""""" KEY REMAPPINGS """""
inoremap jj <Esc>
let mapleader = "\<Space>"
nnoremap <Leader>vs :source ~/.vim/vimrc<CR>
nnoremap <Leader>ve :e ~/.vim/vimrc<CR>
nnoremap <silent> <C-p> :Files<CR>
nnoremap <silent> <Leader>p :Rg<CR>
" nnoremap <silent> <Leader>p :Buffers<CR>

nnoremap <silent> <Leader>b :NERDTreeToggle<CR>

nnoremap <Leader>f :noh<return><esc>

inoremap <c-u> <c-g>u<c-u>
inoremap <c-w> <c-g>u<c-w>

nnoremap gp `[v`]

" Training wheels to break bad habits
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>


""""" PLUGIN CONFIGURATION """""
" lightline
set laststatus=2
set noshowmode
let g:lightline = {
  \   'colorscheme': 'nord',
  \   'active': {
  \     'left':[['mode','paste'],['gitbranch','readonly']],
  \     'right': [['lineinfo'], ['percent'], ['filetype']]
  \   },
  \   'component_function': {
  \     'gitbranch': 'fugitive#head',
  \   'filetype': 'MyFiletype',
  \   }
  \}
let g:lightline.separator = {'left': "\ue0b8", 'right': "\ue0be"}
let g:lightline.subseparator = {'left': "\ue0b9", 'right': "\ue0b9"}
set showtabline=2  " Show tabline
function! MyFiletype()
  return winwidth(0) > 70 ? (strlen(&filetype) ? &filetype . ' ' . WebDevIconsGetFileTypeSymbol() : 'no ft') : ''
endfunction

" lightline buffer
let g:lightline.tabline          = {'left': [['buffers']], 'right': []}
let g:lightline.component_expand = {'buffers': 'lightline#bufferline#buffers'}
let g:lightline.component_type   = {'buffers': 'tabsel'}
let g:lightline#bufferline#show_number  = 1
let g:lightline#bufferline#shorten_path = 1
let g:lightline#bufferline#enable_devicons = 1
let g:lightline#bufferline#min_buffer_count = 0
let g:lightline#bufferline#icon_position = 'right'

" FZF
set grepprg=rg\ --vimgrep\ --smart-case\ --follow

" devicons
set encoding=UTF-8
let g:webdevicons_enable_nerdtree = 1

" GitGutter options
set updatetime=100

"Let's viminfo be in .vim folder
if !has('nvim')
    set viminfo+=n~/.vim/viminfo
endif

" indent lines
let g:indentLine_char = '┊'
